name: heroicons
description: Easily use the heroicons set in your Flutter app.
version: 0.10.0
homepage: https://github.com/vaetas/heroicons

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  path: ^1.9.0

dev_dependencies:
  code_builder: ^4.10.1
  dart_style: ^3.0.0
  recase: ^4.1.0

flutter:
  assets:
    - assets/
    - assets/outline/
    - assets/solid/
    - assets/mini/
    - assets/micro/
