name: heroicons
description: Easily use HeroIcons set of SVG icons in your Flutter app. Only outlined version is available right now.
version: 0.2.0
homepage: https://github.com/vaetas/heroicons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  path: ^1.8.0

dev_dependencies:
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  recase: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/outline/
    - assets/solid/
