name: heroicons
description: HeroIcons
version: 0.0.1
author: Vojtech Pavlovsky
homepage: https://github.com/vaetas/heroicons

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  recase: ^3.0.0
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  code_builder: ^3.5.0
  dart_style: ^1.3.7

flutter:
  assets:
    - assets/
    - assets/outline/
